services:
  # PHP-FPM service (handles backend PHP logic)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini
    ports:
      - 9003:9000 # Expose PHP-FPM port if needed for debugging
    networks:
      - laravel_network
    environment:
      # Use .env file variables
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # Nginx service (web server)
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./docker/production/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  # MySQL service (database)
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./docker/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - 5432:5432
    networks:
      - laravel_network

# Docker Networks
networks:
  laravel_network:
    driver: bridge

# Docker Volumes
volumes:
  db_data:
    driver: local
